#!/bin/bash
# a Sample bash script
echo -n Password: 
read -s passwd
cd ./dist
folder="plazueladetoscan"
sshpass -p "$passwd" rsync --exclude=static/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$folder/web" 

folder="cretaricaurte"
sshpass -p "$passwd" rsync --exclude=static/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$folder/web" 

folder="santoriniricaurte"
sshpass -p "$passwd" rsync --exclude=static/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$folder/web" 

folder="bellasuiza"
sshpass -p "$passwd" rsync --exclude=static/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$folder/web" 

folder="horizontesdelcastillo"
sshpass -p "$passwd" rsync --exclude=static/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$folder/web" 

echo "syncronized"
cd ../